version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379" # Expose Redis on localhost
    volumes:
      - redis-data:/data # Persist data on the host
    networks:
      - redis-network

volumes:
  redis-data: # Named volume for data persistence

networks:
  redis-network: # Dedicated network for Redis service
